# Generated by Django 3.1.1 on 2020-12-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_developer', models.CharField(max_length=34)),
                ('d_doc', models.DateField()),
                ('d_employees', models.IntegerField()),
                ('d_networth', models.IntegerField()),
            ],
            options={
                'db_table': 'Developer',
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('n_nationkey', models.AutoField(primary_key=True, serialize=False)),
                ('n_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Nation',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('r_regionkey', models.AutoField(primary_key=True, serialize=False)),
                ('r_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Region',
            },
        ),
        migrations.CreateModel(
            name='Salestime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_firstyear', models.IntegerField(blank=True, null=True)),
                ('st_alltime', models.IntegerField(blank=True, null=True)),
                ('st_game', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'SalesTime',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_publisher', models.CharField(max_length=32)),
                ('p_doc', models.DateField()),
                ('p_employees', models.IntegerField()),
                ('p_networth', models.IntegerField()),
                ('p_nationkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nation')),
            ],
            options={
                'db_table': 'Publisher',
            },
        ),
        migrations.AddField(
            model_name='nation',
            name='n_regionkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.region'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_rank', models.DecimalField(decimal_places=5, max_digits=10)),
                ('g_title', models.CharField(max_length=32)),
                ('g_sales', models.TextField()),
                ('g_genre', models.CharField(max_length=32)),
                ('g_releasedate', models.DateField()),
                ('g_platform', models.CharField(max_length=32)),
                ('g_developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.developer')),
                ('g_publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.publisher')),
            ],
            options={
                'db_table': 'Game',
            },
        ),
        migrations.AddField(
            model_name='developer',
            name='d_nationkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nation'),
        ),
    ]
